# Generated by Django 5.0.4 on 2024-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User_Detail',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_detail',
            new_name='Task',
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=10),
        ),
    ]
